
rem #######################  先刪除記錄檔 ###############

del check_out.txt
del check_out_ok.txt

REM 這些是要執行的 ============

goto start
:start
call check_one.bat A091
call check_one.bat A097
call check_one.bat A098
call check_one.bat A110
call check_one.bat A111
call check_one.bat A112
call check_one.bat A114
call check_one.bat A119
call check_one.bat A120
call check_one.bat A121
call check_one.bat C056
call check_one.bat C057
call check_one.bat C059
call check_one.bat C071
call check_one.bat C073
call check_one.bat C077
call check_one.bat C078
call check_one.bat C097
call check_one.bat C106
call check_one.bat F01
call check_one.bat F02
call check_one.bat F03
call check_one.bat F12
call check_one.bat F24
call check_one.bat F27
call check_one.bat F28
call check_one.bat F29
call check_one.bat G052
call check_one.bat G069
call check_one.bat G083
call check_one.bat G084
call check_one.bat H01
call check_one.bat I01
call check_one.bat J01
call check_one.bat J07
call check_one.bat J10
call check_one.bat J15
call check_one.bat J19
call check_one.bat J20
call check_one.bat J21
call check_one.bat J22
call check_one.bat J23
call check_one.bat J24
call check_one.bat J25
call check_one.bat J26
call check_one.bat J27
call check_one.bat J28
call check_one.bat J29
call check_one.bat J30
call check_one.bat J31
call check_one.bat J32
call check_one.bat J33
call check_one.bat J34
call check_one.bat J35
call check_one.bat J36
call check_one.bat J37
call check_one.bat J38
call check_one.bat J39
call check_one.bat J40
call check_one.bat K05
call check_one.bat K32
call check_one.bat K34
call check_one.bat K35
call check_one.bat K38
call check_one.bat K41
call check_one.bat L115
call check_one.bat L116
call check_one.bat L130
call check_one.bat L131
call check_one.bat L132
call check_one.bat L133
call check_one.bat L135
call check_one.bat L141
call check_one.bat L143
call check_one.bat L149
call check_one.bat L153
call check_one.bat L154
call check_one.bat L155
call check_one.bat L157
call check_one.bat L158
call check_one.bat L162
call check_one.bat L164
call check_one.bat M059
call check_one.bat P154
call check_one.bat P155
call check_one.bat P167
call check_one.bat P168
call check_one.bat P174
call check_one.bat P178
call check_one.bat P179
call check_one.bat P180
call check_one.bat P181
call check_one.bat P182
call check_one.bat P183
call check_one.bat P184
call check_one.bat P185
call check_one.bat P187
call check_one.bat P189
call check_one.bat S06
call check_one.bat T01
call check_one.bat T02
call check_one.bat T03
call check_one.bat T04
call check_one.bat T05
call check_one.bat T06
call check_one.bat T07
call check_one.bat T08
call check_one.bat T09
call check_one.bat T10
call check_one.bat T11
call check_one.bat T12
call check_one.bat T13
call check_one.bat T14
call check_one.bat T15
call check_one.bat T16
call check_one.bat T17
call check_one.bat T18
call check_one.bat T19
call check_one.bat T20
call check_one.bat T21
call check_one.bat T22
call check_one.bat T23
call check_one.bat T24
call check_one.bat T25
call check_one.bat T26
call check_one.bat T27
call check_one.bat T28
call check_one.bat T29
call check_one.bat T30
call check_one.bat T31
call check_one.bat T32
call check_one.bat T33
call check_one.bat T34
call check_one.bat T35
call check_one.bat T36
call check_one.bat T37
call check_one.bat T38
call check_one.bat T39
call check_one.bat T40
call check_one.bat T41
call check_one.bat T42
call check_one.bat T43
call check_one.bat T44
call check_one.bat T45
call check_one.bat T46
call check_one.bat T47
call check_one.bat T48
call check_one.bat T49
call check_one.bat T50
call check_one.bat T51
call check_one.bat T52
call check_one.bat T53
call check_one.bat T54
call check_one.bat T55
call check_one.bat T85
call check_one.bat U205
call check_one.bat U222
call check_one.bat U223
call check_one.bat W01
call check_one.bat W02
call check_one.bat W03
call check_one.bat W04
call check_one.bat W05
call check_one.bat W06
call check_one.bat W07
call check_one.bat W08
call check_one.bat W09
call check_one.bat X01
call check_one.bat X02
call check_one.bat X03
call check_one.bat X04
call check_one.bat X05
call check_one.bat X07
call check_one.bat X08
call check_one.bat X09
call check_one.bat X10
call check_one.bat X11
call check_one.bat X12
call check_one.bat X13
call check_one.bat X14
call check_one.bat X15
call check_one.bat X16
call check_one.bat X17
call check_one.bat X18
call check_one.bat X19
call check_one.bat X20
call check_one.bat X21
call check_one.bat X22
call check_one.bat X23
call check_one.bat X24
call check_one.bat X25
call check_one.bat X26
call check_one.bat X27
call check_one.bat X28
call check_one.bat X29
call check_one.bat X30
call check_one.bat X31
call check_one.bat X32
call check_one.bat X33
call check_one.bat X34
call check_one.bat X35
call check_one.bat X36
call check_one.bat X37
call check_one.bat X38
call check_one.bat X39
call check_one.bat X40
call check_one.bat X41
call check_one.bat X42
call check_one.bat X43
call check_one.bat X44
call check_one.bat X45
call check_one.bat X46
call check_one.bat X47
call check_one.bat X48
call check_one.bat X49
call check_one.bat X50
call check_one.bat X51
call check_one.bat X53
call check_one.bat X54
call check_one.bat X55
call check_one.bat X56
call check_one.bat X57
call check_one.bat X58
call check_one.bat X59
call check_one.bat X60
call check_one.bat X61
call check_one.bat X62
call check_one.bat X63
call check_one.bat X64
call check_one.bat X65
call check_one.bat X66
call check_one.bat X67
call check_one.bat X68
call check_one.bat X69
call check_one.bat X70
call check_one.bat X71
call check_one.bat X72
call check_one.bat X73
call check_one.bat X74
call check_one.bat X75
call check_one.bat X76
call check_one.bat X77
call check_one.bat X78
call check_one.bat X79
call check_one.bat X80
call check_one.bat X81
call check_one.bat X82
call check_one.bat X83
call check_one.bat X84
call check_one.bat X85
call check_one.bat X86
call check_one.bat X87
call check_one.bat X88

goto end
:end
